import type { ArabicTool, ToolCategory } from "@/types";

export const TOOL_CATEGORIES: Record<ToolCategory, { nameAr: string; nameEn: string; icon: string }> = {
  arabic:     { nameAr: "أدوات النصوص العربية", nameEn: "Arabic Text Tools",     icon: "Type" },
  calculators:{ nameAr: "الحاسبات",              nameEn: "Calculators",           icon: "Calculator" },
  pdf:        { nameAr: "أدوات PDF",             nameEn: "PDF Tools",             icon: "FileText" },
  image:      { nameAr: "أدوات الصور",           nameEn: "Image Tools",           icon: "Image" },
  qr:         { nameAr: "مولد QR كود",           nameEn: "QR Code Generator",     icon: "QrCode" },
  developer:  { nameAr: "أدوات المطورين",        nameEn: "Developer Tools",       icon: "Code" },
  converter:  { nameAr: "محولات النصوص",         nameEn: "Text Converters",       icon: "ArrowLeftRight" },
};

export const TOOLS: ArabicTool[] = [
  // ===================== ARABIC TEXT TOOLS (12) =====================
  {
    slug: "aadad-alkaalimat",
    nameAr: "عداد الكلمات والحروف",
    nameEn: "Word & Character Counter",
    descriptionAr: "احسب عدد الكلمات والحروف والجمل في النص العربي مع إحصائيات تفصيلية.",
    category: "arabic",
    icon: "Hash",
    keywords: ["عداد كلمات", "حاسبة حروف", "عدد الجمل", "إحصائيات نص"],
    component: "WordCounter",
    popular: true,
  },
  {
    slug: "izalat-altashkeel",
    nameAr: "إزالة التشكيل",
    nameEn: "Remove Diacritics",
    descriptionAr: "أزل علامات التشكيل والتنقيط من النص العربي بسرعة.",
    category: "arabic",
    icon: "Eraser",
    keywords: ["إزالة تشكيل", "حذف حركات", "تنقيط", "تشكيل"],
    component: "TashkeelRemover",
    popular: true,
  },
  {
    slug: "altarqam-ila-kaalimat",
    nameAr: "الترقيم إلى كلمات",
    nameEn: "Number to Arabic Words",
    descriptionAr: "حوّل الأرقام إلى كلمات عربية مفصلة (مثل: 123 → مئة وثلاثة وعشرون).",
    category: "arabic",
    icon: "SpellCheck",
    keywords: ["رقم إلى كلمات", "تحويل أرقام", "كتابة أرقام بالحروف"],
    component: "NumberToWords",
    popular: true,
    isUnique: true,
  },
  {
    slug: "tahweel-altaareekh",
    nameAr: "تحويل التاريخ الهجري",
    nameEn: "Hijri Date Converter",
    descriptionAr: "حوّل بين التاريخ الهجري والميلادي بدقة عالية مع عرض التاريخ اليوم.",
    category: "arabic",
    icon: "Calendar",
    keywords: ["تحويل هجري", "ميلادي إلى هجري", "تاريخ إسلامي", "هجري"],
    component: "HijriConverter",
    popular: true,
    isUnique: true,
  },
  {
    slug: "lawhat-almafaateeh-alarabiyya",
    nameAr: "لوحة المفاتيح العربية",
    nameEn: "Arabic Keyboard",
    descriptionAr: "اكتب بالعربية باستخدام لوحة مفاتيح افتراضية مع نسخ سهل.",
    category: "arabic",
    icon: "Keyboard",
    keywords: ["لوحة مفاتيح عربية", "كتابة عربية", "كيبورد عربي"],
    component: "ArabicKeyboard",
  },
  {
    slug: "altahweel-alswti",
    nameAr: "التحويل الصوتي",
    nameEn: "Arabic Transliteration",
    descriptionAr: "حوّل النص العربي إلى أحرف لاتينية (فرنكو أرابيك).",
    category: "arabic",
    icon: "Languages",
    keywords: ["تحويل صوتي", "فرنكو", "عربي إلى إنجليزي", "نطق"],
    component: "Transliteration",
  },
  {
    slug: "tatbee-alnass-alarabi",
    nameAr: "تطبيع النص العربي",
    nameEn: "Arabic Text Normalizer",
    descriptionAr: "وحّد أشكال الأحرف العربية المختلفة (أ، إ، آ → ا) لتسهيل البحث.",
    category: "arabic",
    icon: "TextCursor",
    keywords: ["تطبيع نص", "توحيد أحرف", "توحيد الألف", "همزة"],
    component: "TextNormalizer",
  },
  {
    slug: "takrar-alhuruf",
    nameAr: "تكرار الحروف",
    nameEn: "Letter Frequency Analyzer",
    descriptionAr: "احسب تكرار كل حرف في النص العربي مع رسم بياني.",
    category: "arabic",
    icon: "BarChart3",
    keywords: ["تكرار حروف", "إحصائيات", "تحليل نص", "رسم بياني"],
    component: "LetterFrequency",
  },
  {
    slug: "nass-tajreebi-arabi",
    nameAr: "نص تجريبي عربي",
    nameEn: "Arabic Lorem Ipsum",
    descriptionAr: "أنشئ نصاً تجريبياً عربياً للاستخدام في التصميم والتطوير.",
    category: "arabic",
    icon: "FileText",
    keywords: ["لوريم إيبسوم عربي", "نص تجريبي", "نص وهمي", "تصميم"],
    component: "LoremArabic",
  },
  {
    slug: "tahweel-alarqam-alhindiyya",
    nameAr: "تحويل الأرقام الهندية",
    nameEn: "Arabic Numerals Converter",
    descriptionAr: "حوّل بين الأرقام العربية (٠١٢٣) والأرقام الإنجليزية (0123).",
    category: "arabic",
    icon: "Replace",
    keywords: ["أرقام عربية", "أرقام هندية", "تحويل أرقام", "أرقام إنجليزية"],
    component: "NumeralConverter",
  },
  {
    slug: "islaah-ittijah-alnass",
    nameAr: "إصلاح اتجاه النص",
    nameEn: "Text Direction Fixer",
    descriptionAr: "أصلح مشاكل اتجاه النص العربية في النصوص المختلطة.",
    category: "arabic",
    icon: "AlignRight",
    keywords: ["اتجاه نص", "RTL", "من اليمين لليسار", "إصلاح نص"],
    component: "TextDirectionFixer",
  },
  {
    slug: "muqaaranat-alnusus",
    nameAr: "مقارنة النصوص",
    nameEn: "Text Diff Checker",
    descriptionAr: "قارن بين نصين واعرض الفروقات بشكل واضح.",
    category: "arabic",
    icon: "Diff",
    keywords: ["مقارنة نصوص", "فروقات", "diff", "اختلاف"],
    component: "TextDiff",
  },

  // ===================== CALCULATORS (10) =====================
  {
    slug: "haasibat-alzakat",
    nameAr: "حاسبة الزكاة",
    nameEn: "Zakat Calculator",
    descriptionAr: "احسب زكاة مالك بدقة وفق الشريعة الإسلامية (الذهب، الفضة، الأسهم، النقد).",
    category: "calculators",
    icon: "Scale",
    keywords: ["حاسبة زكاة", "زكاة المال", "زكاة الذهب", "زكاة الفضة"],
    component: "ZakatCalculator",
    popular: true,
    isUnique: true,
  },
  {
    slug: "mawaqeet-assalah",
    nameAr: "مواقيت الصلاة",
    nameEn: "Prayer Times",
    descriptionAr: "اعرف مواقيت الصلاة في مدينتك مع إمكانية التخصيص.",
    category: "calculators",
    icon: "Clock",
    keywords: ["مواقيت الصلاة", "أوقات الصلاة", "أذان", "الصلوات الخمس"],
    component: "PrayerTimes",
    popular: true,
    isUnique: true,
  },
  {
    slug: "dareeibat-alqeema-almudaafa-ksa",
    nameAr: "ضريبة القيمة المضافة - السعودية",
    nameEn: "VAT Calculator Saudi Arabia",
    descriptionAr: "احسب ضريبة القيمة المضافة السعودية (15%) بسهولة.",
    category: "calculators",
    icon: "Percent",
    keywords: ["ضريبة قيمة مضافة", "VAT السعودية", "ضريبة 15%", "فاتورة"],
    component: "VatCalculatorSA",
    popular: true,
  },
  {
    slug: "dareeibat-alqeema-almudaafa-uae",
    nameAr: "ضريبة القيمة المضافة - الإمارات",
    nameEn: "VAT Calculator UAE",
    descriptionAr: "احسب ضريبة القيمة المضافة الإماراتية (5%) بسهولة.",
    category: "calculators",
    icon: "Percent",
    keywords: ["ضريبة إماراتية", "VAT الإمارات", "ضريبة 5%", "دبي"],
    component: "VatCalculatorUAE",
  },
  {
    slug: "haasibat-arraatib",
    nameAr: "حاسبة الراتب",
    nameEn: "Salary Calculator",
    descriptionAr: "احسب راتبك الصافي بعد الاستقطاعات والبدلات.",
    category: "calculators",
    icon: "Wallet",
    keywords: ["حاسبة راتب", "صافي الراتب", "استقطاعات", "بدلات"],
    component: "SalaryCalculator",
  },
  {
    slug: "haasibat-alqard",
    nameAr: "حاسبة القرض",
    nameEn: "Loan Calculator",
    descriptionAr: "احسب أقساط القرض والفائدة الإجمالية مع جدولة الدفعات.",
    category: "calculators",
    icon: "Landmark",
    keywords: ["حاسبة قرض", "أقساط", "فائدة", "تمويل"],
    component: "LoanCalculator",
  },
  {
    slug: "muashir-katlat-aljism",
    nameAr: "مؤشر كتلة الجسم",
    nameEn: "BMI Calculator",
    descriptionAr: "احسب مؤشر كتلة جسمك واعرف وزنك المثالي.",
    category: "calculators",
    icon: "Activity",
    keywords: ["BMI", "كتلة الجسم", "وزن مثالي", "صحة"],
    component: "BmiCalculator",
    popular: true,
  },
  {
    slug: "hasibat-assaarat-alharaariyya",
    nameAr: "حاسبة السعرات الحرارية",
    nameEn: "Calorie Calculator",
    descriptionAr: "احسب احتياجك اليومي من السعرات الحرارية لتحقيق أهدافك.",
    category: "calculators",
    icon: "Flame",
    keywords: ["سعرات حرارية", "حرق", "حمية", "دايت"],
    component: "CalorieCalculator",
  },
  {
    slug: "hasibat-alumr",
    nameAr: "حاسبة العمر",
    nameEn: "Age Calculator",
    descriptionAr: "احسب عمرك بالتفصيل: سنوات، أشهر، أيام، ساعات.",
    category: "calculators",
    icon: "CalendarDays",
    keywords: ["حاسبة عمر", "عمري", "العمر بالأيام"],
    component: "AgeCalculator",
  },
  {
    slug: "muharwil-alemlat",
    nameAr: "محول العملات",
    nameEn: "Currency Converter",
    descriptionAr: "حوّل بين العملات العالمية والخليجية بأسعار محدثة.",
    category: "calculators",
    icon: "Coins",
    keywords: ["تحويل عملات", "صرافة", "دولار", "ريال", "درهم"],
    component: "CurrencyConverter",
  },

  // ===================== PDF TOOLS (10) =====================
  {
    slug: "damj-pdf",
    nameAr: "دمج PDF",
    nameEn: "Merge PDF",
    descriptionAr: "ادمج عدة ملفات PDF في ملف واحد بسهولة.",
    category: "pdf",
    icon: "Layers",
    keywords: ["دمج PDF", "جمع ملفات", "PDF واحد"],
    component: "MergePDF",
    popular: true,
  },
  {
    slug: "taqseem-pdf",
    nameAr: "تقسيم PDF",
    nameEn: "Split PDF",
    descriptionAr: "قسّم ملف PDF إلى صفحات منفصلة أو نطاقات.",
    category: "pdf",
    icon: "Scissors",
    keywords: ["تقسيم PDF", "فصل صفحات", "استخراج صفحات"],
    component: "SplitPDF",
  },
  {
    slug: "daght-pdf",
    nameAr: "ضغط PDF",
    nameEn: "Compress PDF",
    descriptionAr: "قلّص حجم ملف PDF مع الحفاظ على الجودة.",
    category: "pdf",
    icon: "FileDown",
    keywords: ["ضغط PDF", "تقليل حجم", "PDF صغير"],
    component: "CompressPDF",
  },
  {
    slug: "pdf-ila-suwar",
    nameAr: "PDF إلى صور",
    nameEn: "PDF to Images",
    descriptionAr: "حوّل صفحات PDF إلى صور JPG أو PNG.",
    category: "pdf",
    icon: "Image",
    keywords: ["PDF إلى صور", "تحويل PDF", "استخراج صور"],
    component: "PdfToJpg",
  },
  {
    slug: "suwar-ila-pdf",
    nameAr: "صور إلى PDF",
    nameEn: "Images to PDF",
    descriptionAr: "حوّل مجموعة صور إلى ملف PDF واحد.",
    category: "pdf",
    icon: "FileImage",
    keywords: ["صور إلى PDF", "تحويل صور", "إنشاء PDF"],
    component: "ImagesToPdf",
  },
  {
    slug: "word-ila-pdf",
    nameAr: "Word إلى PDF",
    nameEn: "Word to PDF",
    descriptionAr: "حوّل مستندات Word إلى PDF بجودة عالية.",
    category: "pdf",
    icon: "FileText",
    keywords: ["Word إلى PDF", "تحويل وورد", "مستند PDF"],
    component: "WordToPdf",
  },
  {
    slug: "excel-ila-pdf",
    nameAr: "Excel إلى PDF",
    nameEn: "Excel to PDF",
    descriptionAr: "حوّل جداول Excel إلى ملفات PDF.",
    category: "pdf",
    icon: "Table",
    keywords: ["Excel إلى PDF", "تحويل إكسل", "جدول PDF"],
    component: "ExcelToPdf",
  },
  {
    slug: "tashrif-pdf",
    nameAr: "تشفير PDF",
    nameEn: "Encrypt PDF",
    descriptionAr: "حمِ ملف PDF بكلمة مرور لمنع الفتح أو النسخ.",
    category: "pdf",
    icon: "Lock",
    keywords: ["تشفير PDF", "حماية PDF", "كلمة مرور PDF"],
    component: "EncryptPDF",
  },
  {
    slug: "fak-tashrif-pdf",
    nameAr: "فك تشفير PDF",
    nameEn: "Unlock PDF",
    descriptionAr: "أزِل كلمة المرور من ملف PDF المحمي.",
    category: "pdf",
    icon: "Unlock",
    keywords: ["فك تشفير PDF", "إزالة كلمة مرور", "PDF محمي"],
    component: "UnlockPDF",
  },
  {
    slug: "elaama-maeiyya-pdf",
    nameAr: "علامة مائية PDF",
    nameEn: "Watermark PDF",
    descriptionAr: "أضِف علامة مائية نصية أو صورة إلى ملف PDF.",
    category: "pdf",
    icon: "Droplet",
    keywords: ["علامة مائية", " watermark", "حماية حقوق"],
    component: "WatermarkPDF",
  },

  // ===================== IMAGE TOOLS (10) =====================
  {
    slug: "daght-assouwar",
    nameAr: "ضغط الصور",
    nameEn: "Compress Images",
    descriptionAr: "قلّص حجم الصور مع الحفاظ على الجودة.",
    category: "image",
    icon: "Minimize2",
    keywords: ["ضغط صور", "تقليل حجم", "تحسين صور"],
    component: "CompressImage",
    popular: true,
  },
  {
    slug: "taghyeer-hajm-assouwar",
    nameAr: "تغيير حجم الصور",
    nameEn: "Resize Images",
    descriptionAr: "غيّر أبعاد الصور بالبكسل أو النسبة المئوية.",
    category: "image",
    icon: "Maximize2",
    keywords: ["تغيير حجم", "تعديل أبعاد", "تحجيم صور"],
    component: "ResizeImage",
    popular: true,
  },
  {
    slug: "png-ila-jpg",
    nameAr: "PNG إلى JPG",
    nameEn: "PNG to JPG",
    descriptionAr: "حوّل صور PNG إلى JPG بجودة قابلة للتعديل.",
    category: "image",
    icon: "Image",
    keywords: ["PNG إلى JPG", "تحويل PNG", "صور JPG"],
    component: "PngToJpg",
  },
  {
    slug: "jpg-ila-png",
    nameAr: "JPG إلى PNG",
    nameEn: "JPG to PNG",
    descriptionAr: "حوّل صور JPG إلى PNG مع دعم الشفافية.",
    category: "image",
    icon: "Image",
    keywords: ["JPG إلى PNG", "تحويل JPG", "صور PNG"],
    component: "JpgToPng",
  },
  {
    slug: "tahweel-ila-webp",
    nameAr: "تحويل إلى WebP",
    nameEn: "Convert to WebP",
    descriptionAr: "حوّل أي صورة إلى صيغة WebP الحديثة.",
    category: "image",
    icon: "Globe",
    keywords: ["WebP", "تحويل صيغة", "صور ويب"],
    component: "ToWebP",
  },
  {
    slug: "qass-assouwar",
    nameAr: "قص الصور",
    nameEn: "Crop Images",
    descriptionAr: "قص الصور واختر الجزء المراد الاحتفاظ به.",
    category: "image",
    icon: "Crop",
    keywords: ["قص صور", "قص", "اقتطاع"],
    component: "CropImage",
  },
  {
    slug: "tadweer-assouwar",
    nameAr: "تدوير الصور",
    nameEn: "Rotate Images",
    descriptionAr: "در الصور بزاوية معينة أو 90 درجة.",
    category: "image",
    icon: "RotateCw",
    keywords: ["تدوير صور", "قلب صور", "استدارة"],
    component: "RotateImage",
  },
  {
    slug: "izalat-alkhalfiyya",
    nameAr: "إزالة الخلفية",
    nameEn: "Remove Background",
    descriptionAr: "أزِل خلفية الصور تلقائياً واحصل على صورة شفافة.",
    category: "image",
    icon: "Eraser",
    keywords: ["إزالة خلفية", "خلفية شفافة", "PNG شفاف"],
    component: "RemoveBg",
    popular: true,
  },
  {
    slug: "idafat-nass-arabi-ala-assouwar",
    nameAr: "إضافة نص عربي على الصور",
    nameEn: "Add Arabic Text to Images",
    descriptionAr: "أضِف نصاً عربياً على صورك مع خيارات خط متعددة.",
    category: "image",
    icon: "Type",
    keywords: ["نص على صورة", "كتابة عربية", "تعديل صور"],
    component: "AddArabicText",
    isUnique: true,
  },
  {
    slug: "heic-ila-jpg",
    nameAr: "HEIC إلى JPG",
    nameEn: "HEIC to JPG",
    descriptionAr: "حوّل صور iPhone (HEIC) إلى JPG عادي.",
    category: "image",
    icon: "Smartphone",
    keywords: ["HEIC", "آيفون", "تحويل صور آبل"],
    component: "HeicToJpg",
  },

  // ===================== QR CODE TOOLS (8) =====================
  {
    slug: "qr-rabat-mawqie",
    nameAr: "QR رابط موقع",
    nameEn: "QR Code URL",
    descriptionAr: "أنشئ QR كود لأي رابط موقع إلكتروني.",
    category: "qr",
    icon: "Link",
    keywords: ["QR رابط", "باركود رابط", "كود QR لموقع"],
    component: "QRGenerator",
    popular: true,
  },
  {
    slug: "qr-whatsapp",
    nameAr: "QR واتساب",
    nameEn: "QR Code WhatsApp",
    descriptionAr: "أنشئ QR كود للتواصل عبر واتساب مباشرة.",
    category: "qr",
    icon: "MessageCircle",
    keywords: ["QR واتساب", "واتساب QR", "باركود واتساب"],
    component: "QRGenerator",
    popular: true,
    isUnique: true,
  },
  {
    slug: "qr-bitaqat-ittisal",
    nameAr: "QR بطاقة اتصال",
    nameEn: "QR Code vCard",
    descriptionAr: "أنشئ QR كود لبطاقة اتصال (vCard) مع الاسم والهاتف.",
    category: "qr",
    icon: "Contact",
    keywords: ["QR اتصال", "vCard", "بطاقة عمل رقمية"],
    component: "QRGenerator",
  },
  {
    slug: "qr-wifi",
    nameAr: "QR واي فاي",
    nameEn: "QR Code WiFi",
    descriptionAr: "أنشئ QR كود لمشاركة بيانات الواي فاي.",
    category: "qr",
    icon: "Wifi",
    keywords: ["QR واي فاي", "مشاركة واي فاي", "باركود شبكة"],
    component: "QRGenerator",
    isUnique: true,
  },
  {
    slug: "qr-nass-arabi",
    nameAr: "QR نص عربي",
    nameEn: "QR Code Arabic Text",
    descriptionAr: "أنشئ QR كود يحتوي على نص عربي.",
    category: "qr",
    icon: "FileText",
    keywords: ["QR نص", "نص عربي QR", "باركود نص"],
    component: "QRGenerator",
  },
  {
    slug: "qr-bareed-elektrowni",
    nameAr: "QR بريد إلكتروني",
    nameEn: "QR Code Email",
    descriptionAr: "أنشئ QR كود لفتح تطبيق البريد مع عنوان جاهز.",
    category: "qr",
    icon: "Mail",
    keywords: ["QR بريد", "إيميل QR", "باركود بريد"],
    component: "QRGenerator",
  },
  {
    slug: "qr-raqm-hatif",
    nameAr: "QR رقم هاتف",
    nameEn: "QR Code Phone",
    descriptionAr: "أنشئ QR كود للاتصال برقم هاتف مباشرة.",
    category: "qr",
    icon: "Phone",
    keywords: ["QR هاتف", "رقم QR", "باركود هاتف"],
    component: "QRGenerator",
  },
  {
    slug: "qr-mawqi-jughraffi",
    nameAr: "QR موقع جغرافي",
    nameEn: "QR Code Location",
    descriptionAr: "أنشئ QR كود لموقع جغرافي (خطوط الطول والعرض).",
    category: "qr",
    icon: "MapPin",
    keywords: ["QR موقع", "موقع جغرافي", "GPS QR"],
    component: "QRGenerator",
  },

  // ===================== DEVELOPER TOOLS (8) =====================
  {
    slug: "munsiq-json",
    nameAr: "منسق JSON",
    nameEn: "JSON Formatter",
    descriptionAr: "نسّق وحقّق من ملفات JSON مع تلوين وتصغير.",
    category: "developer",
    icon: "Braces",
    keywords: ["منسق JSON", "JSON formatter", "تنسيق جيسون"],
    component: "JsonFormatter",
    popular: true,
  },
  {
    slug: "tarmeez-base64",
    nameAr: "ترميز Base64",
    nameEn: "Base64 Encoder/Decoder",
    descriptionAr: "رمّز أو فك ترميز النصوص والصور بصيغة Base64.",
    category: "developer",
    icon: "Binary",
    keywords: ["Base64", "ترميز", "فك ترميز", "encode"],
    component: "Base64Tool",
    popular: true,
  },
  {
    slug: "tarmeez-url",
    nameAr: "ترميز URL",
    nameEn: "URL Encoder/Decoder",
    descriptionAr: "رمّز أو فك ترميز الروابط URL encoding.",
    category: "developer",
    icon: "Link",
    keywords: ["URL encode", "ترميز رابط", "فك ترميز URL"],
    component: "UrlEncoderDecoder",
  },
  {
    slug: "muwallid-kalima-almarur",
    nameAr: "مولد كلمة المرور",
    nameEn: "Password Generator",
    descriptionAr: "أنشئ كلمات مرور قوية وعشوائية.",
    category: "developer",
    icon: "Key",
    keywords: ["مولد كلمات مرور", "كلمة سر", "password generator"],
    component: "PasswordGenerator",
    popular: true,
  },
  {
    slug: "muwallid-uuid",
    nameAr: "مولد UUID",
    nameEn: "UUID Generator",
    descriptionAr: "أنشئ معرفات فريدة UUID/GUID.",
    category: "developer",
    icon: "Fingerprint",
    keywords: ["UUID", "GUID", "معرف فريد"],
    component: "UuidGenerator",
  },
  {
    slug: "muwallid-hash",
    nameAr: "مولد Hash",
    nameEn: "Hash Generator",
    descriptionAr: "أنشئ قيم hash للنصوص (MD5, SHA-1, SHA-256).",
    category: "developer",
    icon: "Hash",
    keywords: ["hash", "MD5", "SHA", "تشفير"],
    component: "HashGenerator",
  },
  {
    slug: "mukhtabar-regex",
    nameAr: "مختبر Regex",
    nameEn: "Regex Tester",
    descriptionAr: "اختبر التعابير النمطية (Regular Expressions) مع تلوين.",
    category: "developer",
    icon: "Terminal",
    keywords: ["regex", "تعابير نمطية", "اختبار regex"],
    component: "RegexTester",
  },
  {
    slug: "muharwil-alawaan",
    nameAr: "محول الألوان",
    nameEn: "Color Converter",
    descriptionAr: "حوّل بين صيغ الألوان: HEX, RGB, HSL.",
    category: "developer",
    icon: "Palette",
    keywords: ["تحويل ألوان", "HEX RGB", "منتقي ألوان"],
    component: "ColorConverter",
  },

  // ===================== CONVERTER TOOLS (7) =====================
  {
    slug: "csv-ila-json",
    nameAr: "CSV إلى JSON",
    nameEn: "CSV to JSON Converter",
    descriptionAr: "حوّل ملفات CSV إلى صيغة JSON.",
    category: "converter",
    icon: "Table",
    keywords: ["CSV إلى JSON", "تحويل CSV", "جدول إلى جيسون"],
    component: "CsvJsonConverter",
  },
  {
    slug: "markdown-ila-html",
    nameAr: "Markdown إلى HTML",
    nameEn: "Markdown to HTML",
    descriptionAr: "حوّل نص Markdown إلى HTML مع معاينة مباشرة.",
    category: "converter",
    icon: "FileCode",
    keywords: ["Markdown إلى HTML", "تحويل ماركداون", "معاينة"],
    component: "MarkdownPreview",
  },
  {
    slug: "tarmeez-html-entities",
    nameAr: "ترميز HTML Entities",
    nameEn: "HTML Entities Encoder/Decoder",
    descriptionAr: "رمّز أو فك ترميز كيانات HTML.",
    category: "converter",
    icon: "Code",
    keywords: ["HTML entities", "كيانات HTML", "ترميز HTML"],
    component: "HtmlEntityTool",
  },
  {
    slug: "nass-ila-athnai",
    nameAr: "نص إلى ثنائي",
    nameEn: "Text to Binary",
    descriptionAr: "حوّل النص إلى نظام ثنائي (0 و 1) والعكس.",
    category: "converter",
    icon: "Binary",
    keywords: ["نص إلى ثنائي", "binary", "تحويل ثنائي"],
    component: "TextToBinary",
  },
  {
    slug: "muwallid-lorem-ipsum",
    nameAr: "مولد Lorem Ipsum",
    nameEn: "Lorem Ipsum Generator",
    descriptionAr: "أنشئ نصاً تجريبياً Lorem Ipsum للتصميم.",
    category: "converter",
    icon: "FileText",
    keywords: ["Lorem Ipsum", "نص تجريبي", "نص وهمي"],
    component: "LoremArabic",
  },
  {
    slug: "tarteeb-alnusus",
    nameAr: "ترتيب النصوص",
    nameEn: "Text Sorter",
    descriptionAr: "رتّب قائمة من النصوص أبجدياً أو عكسياً.",
    category: "converter",
    icon: "ListOrdered",
    keywords: ["ترتيب نصوص", "فرز", "sort"],
    component: "TextSorter",
  },
  {
    slug: "muqaaranat-csv",
    nameAr: "مقارنة CSV",
    nameEn: "CSV Compare",
    descriptionAr: "قارن بين ملفين CSV واعرض الفروقات.",
    category: "converter",
    icon: "GitCompare",
    keywords: ["مقارنة CSV", "فروقات جدول", "compare CSV"],
    component: "CsvJsonConverter",
  },
];

export const getToolBySlug    = (slug: string) => TOOLS.find(t => t.slug === slug);
export const getPopularTools  = ()             => TOOLS.filter(t => t.popular);
export const getUniqueTools   = ()             => TOOLS.filter(t => t.isUnique);
export const getByCategory    = (cat: ToolCategory) => TOOLS.filter(t => t.category === cat);

// Required by Next.js app router for static generation
export function generateStaticParams() {
  return TOOLS.map(t => ({ slug: t.slug }));
}
